<?php

use Zend\Json\Json;
use Zend\Form\Form;


$columnsTranslatable = $this->grid->getDataSource()->getColumnsTranslatable();
$columnsTranslatableKeys = array_fill_keys($columnsTranslatable, true);
$grid = $this->grid;
$form = $this->grid->getForm();
$instanceView = $this;
$form instanceof Form;

$printForm = function() use($form, $columnsTranslatableKeys, $instanceView) {
    
    $form->prepare();
    $form->setAttribute('action', $instanceView->url(null, array(), array(), true));
    $form->setAttribute('method', 'post');
    $localeElement = $form->get('locale');
    
    $flag = $instanceView->delCountriesFlagsFlag(Locale::getRegion($localeElement->getValue()), 'tiny');
    
    $form->setAttribute('id', 'datagrid-form-' . $localeElement->getValue());
    $form->setAttribute('class', 'form-horizontal grid-form');
    
    
    $instanceView->zfJoacubFormJqueryValidatePrepare('create-form');
    echo $instanceView->form()->openTag($form);
    ?>
    
    <?php foreach ($form->getElements() as $element): ?>
<div class="control-group">
            <?php if ($element->getAttribute('type') == 'hidden'): ?>
                <?php echo $instanceView->formHidden($element) ?>
            <?php else: ?>
                <?php $element->setLabelAttributes(array('class' => 'control-label')); ?>
                <?php 
                if ($element->getLabel())
            	{
            		echo $instanceView->formLabel($element);
            	}
            	?>
                <div class="controls">
                    <?php echo $instanceView->formElement($element)  ?> <?php echo isset($columnsTranslatableKeys[$element->getName()]) ? $flag : '' ?>
                    <p class="help-block">
                        <?php echo $instanceView->formElementErrors($element); ?>
                    </p>
	</div>
            <?php endif; ?>
        </div>
<?php endforeach; ?>

<div class="form-actions">
	<button type="submit" class="btn btn-info">Save</button>
</div>

<?php echo $instanceView->form()->closeTag();
};


if($grid->getDataSource()->isTranslationTable()) :
$localeElement = $form->get('locale');
$localeElement->setAttribute('type', 'hidden');
$locales = $this->joacubBaseLocale()->getLocaleSupported();
?>
<div class="tabbable">
	<!-- Only required for left/right tabs -->
	<ul id="tabslangs" class="nav nav-tabs">
	<?php foreach ($locales as $locale):  ?>
		<li <?php echo $localeElement->getValue() !== $locale ? null : 'class="active"'?>><a href="<?php echo $this->joacubBaseQueryParams(array('locale' => $locale), true); ?>#tab-joacub-crud-locale-<?php echo $locale ?>" data-toggle="tab"><?php echo ucfirst(Locale::getDisplayLanguage($locale)) ?></a></li>
		<?php endforeach; ?>
	</ul>
	<div class="tab-content">
	<?php foreach($locales as $locale): ?>
	
		<div class="tab-pane <?php echo $localeElement->getValue() !== $locale ? null : 'active'?>" id="tab-joacub-crud-locale-<?php echo $locale ?>">
			<?php $localeElement->getValue() !== $locale ?: $printForm(); ?>
		</div>
		<?php endforeach; ?>
	</div>
</div>

<?php 
endif;

?>

<script type="text/javascript">
//<!--

$('#tabslangs a').on('shown', function (e) {
    var parts = $(this).attr('href').split('#');
    
    var relateTarget = e.relatedTarget + '';
    var partsRelateTarget = relateTarget.split('#');

    var $relateTab = $('#' + partsRelateTarget[1]);
    var $tab = $('#' + parts[1]);

    if($tab.find('form').length == 0) {

    	$tab.height(200);
        
        $tab.block({ message: '<img  src="<?php echo $this->basePath(); ?>/img/at-datagrid/ajax-loader.gif" alt="Cargando..." >', css: {height:'128px', width:'128px', background: 'transparent', border: 'none'} });
        
    	var iframe = $('<iframe>').hide().attr('src', $(this).attr('href')).load(function() {
    	    var content = $(this).contents().find('#tabslangs + .tab-content #'+$tab.attr('id')).html();
    	    $tab.html(content);
    	    $tab.height('auto');
    	    $(this).contents().find('body').find("script:contains(\"validate\")").each(function(i) {
                eval($(this).text());
            });

            $(this).remove();
            $tab.unblock();
    	});
    	
    	$('body').append(iframe);
    }
    	
    
    
    })
    
    var columnsTranslatable = <?php echo Json::encode($columnsTranslatable); ?>;
    $('input, textarea').on('change', function() {
    	if(columnsTranslatable[$(this).attr('name')]) {
    	    $('[name="'+$(this).attr('name')+'"]').val($(this).val());
    	}
    });
//-->
</script>

