<?php $this->headScript()->appendFile($this->basePath() . '/js/zf-joacub-crud/datagrid.js') ?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/zf-joacub-crud/jquery.blockUI.js') ?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/zf-joacub-crud/datagrid.css') ?>
<?php 
$actionsIcons = array(
    'delete' => '<i class="icon-trash"></i>',
    'edit' => '<i class="icon-edit"></i>'
);
?>

<h2><?php echo $this->translate($this->gridManager->getGrid()->getCaption()) ?></h2>
<p>
	<a class="btn"
		title="<?php echo $this->translate($this->gridManager->getGrid()->getCaptionBackTo()); ?>"
		href="<?php echo $this->backUrl ?>"> <i class="icon-circle-arrow-left"></i>
        <?php echo $this->translate($this->gridManager->getGrid()->getCaptionBackTo()); ?>
        </a>
</p>

<?php echo $this->render('zf-joacub-crud/item/info')?>

<div class="btn-group right pull-right">
	<a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->translate('actions')?> <span
		class="caret"></span></a>
	<ul class="dropdown-menu">
                <?php foreach($this->gridManager->getActions() as $action) : ?>
                    <li><a href=""
			<?php if (isset($action['confirm-message'])): ?>
			onclick="return DataGrid.confirmAction(this, '<?php echo $action['confirm-message'] ?>')"
			<?php endif;?>>
					<?php echo isset($actionsIcons[$action['action']]) ? $actionsIcons[$action['action']] : ''?>
                            <?php echo $this->translate($action['label'])?>
                        </a></li>
                <?php endforeach; ?>
            </ul>
</div>

<div class="tabbable tabs-left clear">
	<ul class="nav nav-tabs">
        <?php if ($this->showSummaryTab): ?>
            <li
			<?php if ($this->panel == 'summary' || !$this->panel): ?>
			class="active" <?php endif;?>><a href="#summary" data-toggle="tab">información
				general</a></li>
        <?php endif; ?>

        <li
			<?php if ($this->panel == 'data' || !$this->showSummaryTab): ?>
			class="active" <?php endif;?>><a href="#data" data-toggle="tab">Edición
				de datos</a></li>

        <?php foreach ($this->gridManager->getGrid()->getDataPanels() as $key => $panel): ?>
            <li <?php if ($this->panel == $key): ?> class="active"
			<?php endif;?>>
                <?php if ($panel['is_ajax']): ?>
                    <a href="#<?php echo $key ?>" data-toggle="tab"
			onclick="DataGrid.loadDataPanel('', '<?php echo $key ?>');">
                        <?php echo $panel['name'] ?>
                    </a>
                <?php else: ?>
                    <a href="">
                        <?php echo $panel['name'] ?>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
	<div class="tab-content">
        
        <?php if ($this->showSummaryTab): ?>
            <div
			class="tab-pane<?php if ($this->panel == 'summary' || !$this->panel): ?> active<?php endif;?>"
			id="summary">
                <?php echo $this->viewPanelsSumary ?>
            </div>
        <?php endif;?>

        <div
			class="tab-pane<?php if ($this->panel == 'data' || !$this->showSummaryTab): ?> active<?php endif;?>"
			id="data">
            <?php echo $this->viewForm ?>
        </div>

        <?php foreach ($this->gridManager->getGrid()->getDataPanels() as $key => $panel): ?>
            <div
			class="tab-pane<?php if ($this->panel == $key): ?> active<?php endif;?>"
			id="<?php echo $key ?>"></div>
        <?php endforeach; ?>
    </div>
</div>

<?php if ($this->panel) : ?>
<script type="text/javascript">
        DataGrid.loadDataPanel('', '<?php echo $key ?>');
    </script>
<?php endif ?>
