<?php

$form = $this->grid->getFiltersForm();
$form->prepare();
$form->setAttribute('action', $this->url(null, array('action' => 'list')));
$form->setAttribute('method', 'get');
$form->setAttribute('id', 'datagrid-filters-form');
$filtersClean = array();
echo $this->form()->openTag($form);
?>

    <tr class="filters">
        <td><!--  --></td>
        <?php foreach ($this->grid as $column) : ?>
            <?php if ($column->isVisible()): ?>
            <td>
                <?php if ($column->hasFilters()): ?>
                    <?php foreach ($column->getFilters() as $filter) : ?>
                        <?php $filtersClean[$filter->getName()] = null; ?> 
                        <?php echo $this->formElement($form->get($filter->getName())); ?>
                    <?php endforeach; ?>    
                <?php endif; ?>
            </td>
            <?php endif; ?>
        <?php endforeach; ?>
        <td>
            <div class="btn-group right">
                <button class="btn btn-info btn-small" type="submit" title="<?php echo $this->translate('Apply filters'); ?>"><i class="icon-search icon-white"></i></button>
                <a class="btn btn-danger btn-small" href="<?php echo $this->url(null, $filtersClean, true)?>" title="<?php echo $this->translate('Reset filters'); ?>"><i class="icon-remove icon-white"></i></a>
            </div>
        </td>
    </tr>
<?php echo $this->form()->closeTag(); ?>