<?php
$messages = $this->flashMessenger()->render(
    SuperMessenger\Controller\Plugin\SuperMessenger::SUCCESS_MESSAGE);
if($messages)
    echo str_replace(array(
        '&times;'
    ), array(
        '<i class="icon-remove-circle"></i>'
    ), (string) $this->sxbAlert()->success($messages));

$messages = $this->flashMessenger()->render(
    SuperMessenger\Controller\Plugin\SuperMessenger::ERROR_MESSAGE);
if($messages)
    echo str_replace(array(
        '&times;'
    ), array(
        '<i class="icon-remove-circle"></i>'
    ), (string) $this->sxbAlert()->error($messages));

$messages = $this->flashMessenger()->render(
    SuperMessenger\Controller\Plugin\SuperMessenger::INFO_MESSAGE);
if($messages)
    echo str_replace(array(
        '&times;'
    ), array(
        '<i class="icon-remove-circle"></i>'
    ), (string) $this->sxbAlert()->info($messages));
?>
<h2><?php echo $this->translate($this->grid->getCaption()) ?></h2>
<?php if ($this->grid->isAllowCreate()): ?>
<a class="btn btn-warning"
	href="<?php echo $this->url(null, array('action' => 'create')) ?>"><?php echo $this->translate('Create new') ?> <i
	class="icon-plus-sign"></i></a>
<?php endif; ?>

        <?php echo $this->viewGridPaginator; ?>
<hr />

<div class="atf-grid">
	<table class="table table-striped">
		<thead>
			<tr>
				<th><input type="checkbox" onclick="DataGrid.checkAll(this)" /></th>
                        <?php foreach ($this->grid as $column) : ?>
                            <?php if ($column->isVisible()): ?>
                                <th>
                                    <?php if ($column->isSortable()): ?>
                                        <a class="sortable"
					href="<?php echo $this->joacubBaseQueryParams(array('page' => 1, 'order' => $column->getName() . '~' . $column->getOrderDirection())) ?>">
                                            <?php if ($this->grid->getCurrentOrderColumnName() == $column->getName()): ?>
                                                <span class="active">
                                                    <?php echo $column->getLabel()?>
                                                    <?php if ($this->grid->getCurrentOrderDirection() == 'asc'): ?>
                                                        &uarr;
                                                    <?php elseif($this->grid->getCurrentOrderDirection() == 'desc'): ?>
                                                        &darr;
                                                    <?php endif; ?>
                                                </span>
                                            <?php else: ?>
                                                <?php echo $column->getLabel()?>
                                            <?php endif; ?>
                                        </a>
                                    <?php else: ?>
                                        <?php echo $column->getLabel()?>
                                    <?php endif; ?>
                                </th>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <th style="width: <?php echo count($this->grid->getButtonActions())*50+30 ?>px;"></th>
			</tr>
		</thead>
		<tbody>

                    <?php echo $this->viewGridFilters ?>

                    <?php if (count($this->rows)): ?>
                    
                        <?php echo $this->viewGridRowsList ?>
                    <?php endif ?>

                </tbody>
	</table>
            <?php if (!count($this->rows)): ?>
                <div><?php echo $this->translate("No items found.") ?></div>
            <?php endif ?>
        </div>

<?php if (count($this->rows)): ?>
            <?php echo $this->viewGridRowsGoupActions ?>
        <?php endif; ?>

<hr />
<?php echo $this->viewGridPaginator; ?>
